### ISSUE TITLE
NPM install yields no global angle command via command line

### ISSUE THREAD

**Issue by Tswan** [aframevr/angle#10]
Hello, 

Very interesting software, and I'm eager to test it it out. I attempt an install using npm using`npm install -g angle` and the software did install, but I can't find a bin directory containing any executables and the angle command cannot be found.

Is there some other file I should be referencing in my bash profile to reference the the angle command? I'm working on a Macbook pro if that makes any difference.

Travis

**Comment by ngokevin** [comment]
It should just work:

http://stackoverflow.com/questions/5817874/how-do-i-install-a-module-globally-using-npm
https://docs.npmjs.com/cli/install

See:

`npm list --global`

And try other packages to see if they work.

**Comment by Tswan** [comment]
Awesome thank you for that helpful link. It took some digging through my system folders, but the was a folder in node `node/5.4.0/bin/` that contained the alias file that runs the angle command in my terminal. After adding that to my bash profile it worked like a charm!
