### ISSUE TITLE
ghpages OR/AND exaples AND component aframe-registry

### ISSUE THREAD

**Issue by 7dir** [aframevr/angle#12]
## It`s only my point of view

what I`m talking about?

```json
    "preghpages": "npm run build && shx rm -rf gh-pages && shx mkdir gh-pages && shx cp -r examples/* gh-pages",
    "ghpages": "npm run preghpages && ghpages -p gh-pages",
```

it\`s bad practice: no sources
it is good for **commercial** usage, just show example

### ghpages aka source code

- I thought we should upload full component repository with source (like polymer web-components)
- add license (done)
- add readme (done)
- git init && git add -A && git commit -m 'git aframe-COMPONENT_NAME-component' (it`s not neccasary)
- git remote add origin https://github.com/USERNAME/aframe-COMPONENT_NAME-component.git (it`s not neccasary too)

```
Usage
  $ ghpages

Options
  -p, --path    Path (directory to push; defaults to current directory)
  -r, --repo    Repository (GitHub username, GitHub username/repo, full repo URL)
  -d, --domain  Domain name (for `CNAME` to create in GitHub Pages branch)
  -p, --path    Path or directory to publish. Defaults to root directory of project.
  -h, --help    Show help

Examples
  $ ghpages
  $ ghpages cvan
  $ ghpages cvan/blog
  $ ghpages cvan/blog -p dist
  $ ghpages git@github.com:cvan/blog.git
  $ ghpages -r cvan/blog -d blog.cvan.io
```

## Deploy

I surpose just add now

```
   "deploy": "ghpages -r {{ repo }}",
```

## A-Frame Registry

It would be great to add only good component
Web-components Registry have bad practice allow everyone to publish component, then it look like 
scrap-heap :-)

I don`t know how A-Frame team add component to Registry
Manualy?

**Comment by 7dir** [comment]
Oh, sorry!

ghpages did not create repo for U

I don\`t like it (ghpages) or just want to sleep )))

### Question about publish still open

**Comment by ngokevin** [comment]
GitHub Pages is the component's homepage.

Registry submission is curated. All Registry submissions usually have a GitHub Pages.

**Comment by 7dir** [comment]
https://github.com/node-gh/gh

this will create repo
```sh
$ npm i gh -g
$ gh re --new aframe-foo-component --gitignore Node
First we need authorization to use GitHub\'s API. Login with your GitHub account.
? Enter your GitHub user 7dir
? Enter your GitHub password ************
Writing GH config data: C:\Users\Administrator\.gh.json
Authentication succeed.
Creating a new repo on 7dir/aframe-foo-component
https://github.com/7dir/aframe-foo-component
[hook] gh re --browser  --user 7dir --repo aframe-foo-component
```

@ngokevin what about add this features?

**Comment by 7dir** [comment]
@ngokevin 

could add this component/packages.json?

```json
  "mkrepo": "gh re --new {{ npmName }} --gitignore Node",
```

or U should add it to README.md

```
To publish the component to the ecosystem:
make sure github repo exist
```

**Comment by ngokevin** [comment]
Yeah I think that's a good idea. A command to create a GitHub repo.
